In [14]:
import xarray as xr
import pandas as pd
import numpy as np
import rasterio 
from datetime import timedelta, date
import matplotlib.pyplot as plt
import h5py
import os

In [2]:
# 2010 soil moisture data (daily measurements stacked into one dataset)
ds_2010 = xr.open_mfdataset('C:\\Users\\Research\\Documents\\Tara_Fall_2019\\ESA_SoilMoisture\\2010\\*.nc')

C:\Users\Research\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: In xarray version 0.15 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  
C:\Users\Research\Anaconda3\lib\site-packages\xarray\backends\api.py:933: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option to
open_mfdataset).
  from_openmfds=True,


In [3]:
# 2016 soil moisture data (daily measurements stacked into one dataset)
ds_2016 = xr.open_mfdataset('C:\\Users\\Research\\Documents\\Tara_Fall_2019\\ESA_SoilMoisture\\2016\\*.nc')

C:\Users\Research\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: In xarray version 0.15 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  
C:\Users\Research\Anaconda3\lib\site-packages\xarray\backends\api.py:933: FutureWarning: The datasets supplied have global dimension coordinates. You may want
to use the new `combine_by_coords` function (or the
`combine='by_coords'` option to `open_mfdataset`) to order the datasets
before concatenation. Alternatively, to continue concatenating based
on the order the datasets are supplied in future, please use the new
`combine_nested` function (or the `combine='nested'` option to
open_mfdataset).
  from_openmfds=True,


In [9]:
smap = xr.open_mfdataset('C:\\Users\\Research\\Documents\\Tara_Fall_2019\\SMAP_SoilMoisture\\smap_2016\\*001E14N_R16010_001.h5', concat_dim = ['longitude_3km', 'latitude_3km'] , engine = 'h5netcdf')

C:\Users\Research\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: In xarray version 0.15 the default behaviour of `open_mfdataset`
will change. To retain the existing behavior, pass
combine='nested'. To use future default behavior, pass
combine='by_coords'. See
http://xarray.pydata.org/en/stable/combining.html#combining-multi

  """Entry point for launching an IPython kernel.


In [10]:
smap

<xarray.Dataset>
Dimensions:     (concat_dim: 2)
Coordinates:
  * concat_dim  (concat_dim) <U13 'longitude_3km' 'latitude_3km'
Data variables:
    *empty*

In [3]:
sm = smap_sample['Soil_Moisture_Retrieval_Data_3km']
print (sm.keys())
sm_3k = sm['soil_moisture_3km']
lat = sm['latitude_3km']
lon = sm['longitude_3km']

<KeysViewHDF5 ['EASE_column_index_3km', 'EASE_column_index_apm_3km', 'EASE_row_index_3km', 'EASE_row_index_apm_3km', 'SMAP_Sentinel_overpass_timediff_hr_3km', 'SMAP_Sentinel_overpass_timediff_hr_apm_3km', 'albedo_3km', 'albedo_apm_3km', 'bare_soil_roughness_retrieved_3km', 'bare_soil_roughness_retrieved_apm_3km', 'beta_tbv_vv_3km', 'beta_tbv_vv_apm_3km', 'disagg_soil_moisture_3km', 'disagg_soil_moisture_apm_3km', 'disaggregated_tb_v_qual_flag_3km', 'disaggregated_tb_v_qual_flag_apm_3km', 'gamma_vv_xpol_3km', 'gamma_vv_xpol_apm_3km', 'landcover_class_3km', 'landcover_class_apm_3km', 'latitude_3km', 'latitude_apm_3km', 'longitude_3km', 'longitude_apm_3km', 'retrieval_qual_flag_3km', 'retrieval_qual_flag_apm_3km', 'sigma0_incidence_angle_3km', 'sigma0_incidence_angle_apm_3km', 'sigma0_vh_aggregated_3km', 'sigma0_vh_aggregated_apm_3km', 'sigma0_vv_aggregated_3km', 'sigma0_vv_aggregated_apm_3km', 'soil_moisture_3km', 'soil_moisture_apm_3km', 'soil_moisture_std_dev_3km', 'soil_moisture_std_d

In [26]:
np.asarray(lat).shape

(90, 87)

In [84]:
smap_sample = h5py.File('C:\\Users\\Research\\Documents\\Tara_Fall_2019\\SMAP_SoilMoisture\\smap_2016\\SMAP_L2_SM_SP_1AIWDV_20160112T053528_20160111T175507_003E13N_R16010_001.h5', "r")
sm = smap_sample['Soil_Moisture_Retrieval_Data_3km']
sm_3k = np.array(sm['soil_moisture_3km'])
print (np.count_nonzero(sm_3k == -9999.0))

smap_sample2 = h5py.File('C:\\Users\\Research\\Documents\\Tara_Fall_2019\\SMAP_SoilMoisture\\smap_2016\\SMAP_L2_SM_SP_1AIWDV_20161130T054744_20161130T175518_003E13N_R16010_001.h5', "r")
sm2 = smap_sample2['Soil_Moisture_Retrieval_Data_3km']
sm_3k2 = np.array(sm2['soil_moisture_3km'])
print (np.count_nonzero(sm_3k2 == -9999.0))

4733
2131


In [86]:
smap_sample.keys()

<KeysViewHDF5 ['Metadata', 'Soil_Moisture_Retrieval_Data_1km', 'Soil_Moisture_Retrieval_Data_3km', 'a']>

In [73]:
sm_3k + sm_3k2

array([[-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       ...,
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.],
       [-9999., -9999., -9999., ..., -9999., -9999., -9999.]],
      dtype=float32)

In [68]:
2 + 0

2

In [111]:
data1 = np.zeros(shape=(84, 84))
count1 = 0

directory = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\SMAP_SoilMoisture\\smap_2016"
for filename in os.listdir(directory):
    if filename.endswith("003E13N_R16010_001.h5"): 
        count1 += 1
#         input_sm = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\SMAP_SoilMoisture\\smap_2016\\" + filename
#         sm = h5py.File(input_sm, "r")
#         sm_data = sm['Soil_Moisture_Retrieval_Data_3km']
#         sm_3k = np.array(sm_data['soil_moisture_3km'])
#         sm_3k[sm_3k<0] = 0
#         re_sized = np.resize(sm_3k,(84, 84))
#         data1 += re_sized
#         count1 += 1

# avg1 = (data1 / count1)
print (count1)

24


In [88]:
type(np.unique(avg1)[0])

numpy.float64

In [91]:
smap_chosen = h5py.File("C:\\Users\\Research\\Documents\\Tara_Fall_2019\\SMAP_SoilMoisture\\smap_2016\\SMAP_L2_SM_SP_1AIWDV_20161213T053600_20161212T175518_003E13N_R16010_001.h5", 'r')
smap_avg = h5py.File("C:\\Users\\Research\\Documents\\Tara_Fall_2019\\SMAP_SoilMoisture\\smap_2016\\average_moisture_2016.h5", "w")

In [107]:
np.array(smap_chosen['Soil_Moisture_Retrieval_Data_3km']['latitude_3km']).shape

(84, 84)

In [94]:
dataset_toadd = smap_avg.create_dataset("annual_average_2016", data = avg1)
dataset_toadd2 = smap_avg.create_dataset("latitude", data = smap_chosen['Soil_Moisture_Retrieval_Data_3km']['latitude_3km'])
dataset_toadd3 = smap_avg.create_dataset("longitude", data = smap_chosen['Soil_Moisture_Retrieval_Data_3km']['longitude_3km'])

In [105]:
df = pd.DataFrame(columns = ["longitude", "latitude", "soil_moisture"])
df["longitude"] = np.array(smap_chosen['Soil_Moisture_Retrieval_Data_3km']['longitude_3km']).flatten()
df["latitude"] = np.array(smap_chosen['Soil_Moisture_Retrieval_Data_3km']['latitude_3km']).flatten()
df["soil_moisture"] = avg1.flatten()


In [110]:
df.to_excel("C:\\Users\\Research\\Documents\\Tara_Fall_2019\\SMAP_SoilMoisture\\smap_2016\\average_moisture_2016xl.xlsx")

In [9]:
#annual soil moisture variation taken over all days in the year
annual_std_2016 = ds_2016.sm.std(dim = 'time')
annual_std_2016 = annual_std_2016.rename('annual_2016_std')
annual_std_2010 = ds_2010.sm.std(dim = 'time')
annual_std_2010 = annual_std_2010.rename('annual_2010_std')

#seasonal soil moisture averages taken over all days in the year
seasonal_2016_std = ds_2016.sm[121:274].std(dim = 'time')
seasonal_2016_std = seasonal_2016_std.rename('seasonal_2016_std')
seasonal_2010_std = ds_2010.sm[121:274].std(dim = 'time')
seasonal_2010_std = seasonal_2010_std.rename('seasonal_2010_std')

In [13]:
#annual soil moisture averages taken over all days in the year
annual_mean_2016 = ds_2016.sm.mean(dim = 'time')
annual_mean_2016 = annual_mean_2016.rename('annual_2016_mean')
annual_mean_2010 = ds_2010.sm.mean(dim = 'time')
annual_mean_2010 = annual_mean_2010.rename('annual_2010_mean')

#annual soil moisture uncertainty averages taken over all days in the year
annual_unc_mean_2016 = ds_2016.sm_uncertainty.mean(dim = 'time')
annual_unc_mean_2016 = annual_unc_mean_2016.rename('annual_unc_2016_mean')
annual_unc_mean_2010 = ds_2010.sm_uncertainty.mean(dim = 'time')
annual_unc_mean_2010 = annual_unc_mean_2010.rename('annual_unc_2010_mean')

In [5]:
#annual soil moisture minimum taken over all days in the year
annual_2016_min = ds_2016.sm.min(dim= 'time')
annual_2016_min = annual_2016_min.rename('annual_2016_min')
annual_2010_min = ds_2010.sm.min(dim = 'time')
annual_2010_min = annual_2010_min.rename('annual_2010_min')

In [6]:
#annual soil moisture maximum taken over all days in the year
annual_2016_max = ds_2016.sm.max(dim= 'time')
annual_2016_max = annual_2016_max.rename('annual_2016_max')
annual_2010_max = ds_2010.sm.max(dim = 'time')
annual_2010_max = annual_2010_max.rename('annual_2010_max')

In [7]:
#seasonal soil moisture averages taken over all days in the year
seasonal_2016_mean = ds_2016.sm[121:274].mean(dim = 'time')
seasonal_2016_mean = seasonal_2016_mean.rename('seasonal_2016_mean')
seasonal_2010_mean = ds_2010.sm[121:274].mean(dim = 'time')
seasonal_2010_mean = seasonal_2010_mean.rename('seasonal_2010_mean')

In [8]:
#seasonal soil moisture minimum taken over all days in the year
seasonal_2016_min = ds_2016.sm[121:274].min(dim = 'time')
seasonal_2016_min = seasonal_2016_min.rename('seasonal_2016_min')
seasonal_2010_min = ds_2010.sm[121:274].min(dim = 'time')
seasonal_2010_min = seasonal_2010_min.rename('seasonal_2010_min')

In [9]:
#seasonal soil moisture maximum taken over all days in the year
seasonal_2016_max = ds_2016.sm[121:274].max(dim = 'time')
seasonal_2016_max = seasonal_2016_max.rename('seasonal_2016_max')
seasonal_2010_max = ds_2010.sm[121:274].max(dim = 'time')
seasonal_2010_max = seasonal_2010_max.rename('seasonal_2010_max')

In [93]:
soil_moisture_annual = xr.merge([annual_mean_2016, annual_mean_2010, annual_2016_min, annual_2010_min, annual_2016_max, annual_2010_max])
soil_moisture_seasonal = xr.merge([seasonal_2016_mean, seasonal_2010_mean, seasonal_2016_min, seasonal_2010_min, seasonal_2016_max, seasonal_2010_max])
uncertainty_mean = xr.merge([annual_unc_mean_2016, annual_unc_mean_2010])


In [10]:
soil_moisture_variation = xr.merge([annual_std_2016, annual_std_2010, seasonal_2016_std, seasonal_2010_std])

In [19]:
soil_moisture_variation.to_netcdf('C:\\Users\\Research\\Documents\\Tara_Fall_2019\\ESA_SoilMoisture\\soil_moisture_variation.nc', 'w', 'NETCDF4')

C:\Users\Research\Anaconda3\lib\site-packages\dask\array\numpy_compat.py:38: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)


In [92]:
soil_moisture_annual.to_netcdf('C:\\Users\\Research\\Documents\\Tara_Fall_2019\\ESA_SoilMoisture\\soil_moisture_annual.nc', 'w', 'NETCDF4')
soil_moisture_seasonal.to_netcdf('C:\\Users\\Research\\Documents\\Tara_Fall_2019\\ESA_SoilMoisture\\soil_moisture_seasonal.nc', 'w', 'NETCDF4')
uncertainty_mean.to_netcdf('C:\\Users\\Research\\Documents\\Tara_Fall_2019\\ESA_SoilMoisture\\uncertainty_mean.nc', 'w', 'NETCDF4')

C:\Users\Research\Anaconda3\lib\site-packages\dask\compatibility.py:107: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)
C:\Users\Research\Anaconda3\lib\site-packages\toolz\functoolz.py:488: RuntimeWarning: All-NaN slice encountered
  ret = f(ret)
C:\Users\Research\Anaconda3\lib\site-packages\dask\array\numpy_compat.py:38: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
C:\Users\Research\Anaconda3\lib\site-packages\dask\compatibility.py:107: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)
C:\Users\Research\Anaconda3\lib\site-packages\toolz\functoolz.py:488: RuntimeWarning: All-NaN slice encountered
  ret = f(ret)
C:\Users\Research\Anaconda3\lib\site-packages\dask\array\numpy_compat.py:38: RuntimeWarning: invalid value encountered in true_divide
  x = np.divide(x1, x2, out)
C:\Users\Research\Anaconda3\lib\site-packages\dask\array\numpy_compat.py:38: RuntimeWarning: invalid value encountered in true_d

In [27]:
np.unique(ds_2016.sm.max(dim= 'time').values, return_counts = True)

C:\Users\Research\Anaconda3\lib\site-packages\dask\compatibility.py:107: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)
C:\Users\Research\Anaconda3\lib\site-packages\toolz\functoolz.py:488: RuntimeWarning: All-NaN slice encountered
  ret = f(ret)


(array([3.4460125, 3.9001238, 4.0048327, ...,       nan,       nan,
              nan], dtype=float32),
 array([1, 1, 1, ..., 1, 1, 1], dtype=int64))